
default_platform :android

platform :android do
  lane :screenshot do
    gradle(
      task: 'clean assembleDebug assembleAndroidTest'
    )

    apk_path = Dir.glob("../**/*-debug.apk").first
    test_apk_path = Dir.glob("../**/*-debug-androidTest.apk").first

    screengrab(
      app_package_name: 'com.nicolasguillen.kointlin',
      app_apk_path: File.absolute_path(apk_path),
      tests_apk_path:  File.absolute_path(test_apk_path)
    )
  end

  lane :aab_release do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )

    puts "AABs: #{Actions.lane_context[SharedValues::GRADLE_ALL_AAB_OUTPUT_PATHS]}"
    puts "AAB: #{Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"

    supply(
          track: "production",
          json_key: "app/upload.json",
          package_name: "com.nicolasguillen.kointlin",
          skip_upload_metadata: false,
          skip_upload_images: true,
          skip_upload_apk: true,
          skip_upload_aab: false
        )
  end

  lane :apk_release do
    gradle(
      task: 'assembleRelease'
    )

    supply(
      track: "production",
      apk: "app/build/outputs/apk/release/app-release.apk",
      json_key: "app/upload.json",
      package_name: "com.nicolasguillen.kointlin",
      skip_upload_metadata: false,
      skip_upload_images: true
    )
  end

end
