# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :screenshot do
    gradle(
      task: 'clean assembleDebug assembleAndroidTest'
    )

    apk_path = Dir.glob("../**/*-debug.apk").first
    test_apk_path = Dir.glob("../**/*-debug-androidTest.apk").first

    screengrab(
      app_package_name: 'com.nicolasguillen.kointlin',
      app_apk_path: File.absolute_path(apk_path),
      tests_apk_path:  File.absolute_path(test_apk_path)
    )
  end

  lane :release do
    gradle(
      task: 'assembleRelease'
    )

    supply(
      track: "beta",
      apk: "app/build/outputs/apk/release/app-release.apk",
      json_key: "app/upload.json",
      package_name: "com.nicolasguillen.kointlin",
      skip_upload_metadata: true,
      skip_upload_images: true
    )
  end

end
